/* tslint:disable */

/* auto-generated by NAPI-RS */

/** 求两个数的和  */
export declare function sum(a: number, b: number): number
/** 请数组所有元素的和  */
export declare function mean(a: Array<number>): number
